### ISSUE TITLE
Masking of graphics::polygon

### ISSUE THREAD

**Issue by mdsumner** [ropensci/geojson#15]
Not sure there's any good solution here, given all the issues re raster/dplyr for non-generics, but this burnt me today.

Maybe polygon.default could hand over to the graphics version for x,y pairs, 2-col matrix, and the other xy list/df cases that aren't explicitly classed?

**Comment by sckott** [comment]
sorry about that. maybe comes from my not using base graphics much. 

> Maybe polygon.default could hand over to the graphics version

is that via `NextMethod` or something else?

**Comment by mdsumner** [comment]
No, but maybe that can work - I'm a bit out of my depth here. 

I submitted a PR that sees whether it can hand over to xy.coords. I also think you should consider changing the name from 'polygon', but I don't have a strong opinion and I don't know what's best.

**Comment by sckott** [comment]
thanks for the PR, having a look

**Comment by mdsumner** [comment]
After discussions about the broader problem I've changed my mind, it's no big deal, it won't affect many. 

If it's easiest to forget this then feel free!

**Comment by sckott** [comment]
Okay. I think in an ideal world we would name it something else, but i think it's easy enough to namespace fxn calls to avoid this. Anyway, thanks for opening the issue anyway!
