### ISSUE TITLE
Error Encountered

### ISSUE THREAD

**Issue by XD-DENG** [ropensci/geojson#17]
Thanks for making this package.

When I tried to run 
```{r}
library(geojson)

x <- "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-99.74,32.45]},\"properties\":{}}]}"
as.geojson(x)
```

I encountered error as below:
```
Error in if (checkforpkg("geojsonlint")) { : 
  argument is not interpretable as logical
In addition: Warning message:
'geojsonlint' not installed, skipping GeoJSON linting 
```
and no useful result returned. 

May you advise why? Maybe I have made any stupid mistake.

**Comment by sckott** [comment]
@XD-DENG Thanks for the issue. 

Please share your `sessionInfo()` so I can see what R version, OS and `geojson` pkg version

**Comment by XD-DENG** [comment]
Hi @sckott , thanks for following up on this. Please find my session info as below. Thanks.

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] geojson_0.1.0

loaded via a namespace (and not attached):
[1] jqr_0.2.4       magrittr_1.5    lazyeval_0.2.0 
[4] tools_3.3.1     sp_1.2-4        Rcpp_0.12.7    
[7] grid_3.3.1      jsonlite_1.2    lattice_0.20-33
```

**Comment by sckott** [comment]
thanks @XD-DENG - that is indeed a bug, would work if you had `geojsonlint` installed, but should work with or without, fixing now

**Comment by sckott** [comment]
@XD-DENG reinstall `devtools::install_github("ropensci/geojson")` and it should work now. 

will get a new version to CRAN soon

**Comment by XD-DENG** [comment]
Thanks @sckott . Confirm it's fixed and I can run the example codes smoothly.

Thanks.

**Comment by sckott** [comment]
great, thanks for reporting it @XD-DENG
