### ISSUE TITLE
failure in properties_add() when passing a variable

### ISSUE THREAD

**Issue by TrantorM** [ropensci/geojson#21]
```
pop <- 1000
x <- '{ "type": "LineString", "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]}'
linestring(x) %>% feature() %>% properties_add(population = pop)
```
The above code gives this error: `No method asJSON S3 class`

The following changes were necessary to make it working:
```
properties_add <- function(x, ...) {
  # tmp <- lazyeval::lazy_dots(...)         # delete this
  tmp <- list(...)                          # add this
  kvpairs <- list()
  for (i in seq_along(tmp)) {
    kvpairs[[names(tmp[i])]] <- tmp[[i]]    # delete $expr
  }
  kvpairsjson <- jsonlite::toJSON(kvpairs, auto_unbox = TRUE)
  jqr::jq(unclass(x), paste0(". | .properties = ", kvpairsjson))
}
```

**Comment by sckott** [comment]
thanks @TrantorM will have a look

**Comment by sckott** [comment]
@TrantorM can you reinstall `devtools::install_github("ropensci/geojson")` and try again 

i went with simpler fix which i should have been using https://github.com/ropensci/geojson/blob/master/R/properties.R#L22 

see also #22  - let me know if you have any thoughts on that - i think it makes more sense to return same object user passes in

**Comment by TrantorM** [comment]
@sckott thanks for the modification. If one wants to add a list of properties, the property names get lost in the geojson file:
```
properties_list = c(
  population = 1000,
  area = 2000,
  density = 3000
)
x <- '{ "type": "LineString", "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]}'
linestring(x) %>% feature() %>% properties_add(properties_list)
```
this results in:
```
{
    "type": "Feature",
    "properties": {
        "1": [
            1000,
            2000,
            3000
        ]
    },
    "geometry": { ...
```
It works if I put all the arguments direct in the function call:
```
linestring(x) %>% feature() %>% properties_add(population = 1000,
  area = 2000,
  density = 3000
)
```
But if you have a bunch of properties, it would be nice to have them inside a list.

**Comment by sckott** [comment]
thx for the additional report @TrantorM , think i know the fix

**Comment by sckott** [comment]
@TrantorM try again after reinstall, see the man page

**Comment by TrantorM** [comment]
thx @sckott for the changes. It works well. The example above is now:
```
properties_list = list(
    population = 1000,
    area = 2000,
    density = 3000
)
x <- '{ "type": "LineString", "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]}'
linestring(x) %>% feature() %>% properties_add(.list=properties_list)
```

**Comment by sckott** [comment]
glad it works
