### ISSUE TITLE
Support for negative coordinates in geo_bbox

### ISSUE THREAD

**Issue by aoles** [ropensci/geojson#33]
Negative geocoordiantes doesn't seem to be properly handled by `geo_bbox`, as in the following example.

```r
x <- '{ "type": "Polygon",
  "coordinates": [
    [ [100.0, 0.0], [101.0, 0.0], [101.0, -1.0], [100.0, -1.0], [100.0, 0.0] ]
  ]
}'
y <- polygon(x)

geo_bbox(y)

## [1] 100   0 101   1
```

I would rather expect the result to be `[1] 100   -1 101   0`.

**Comment by sckott** [comment]
thanks for reoprting this bug, I can replicate it. will have a look at the PR
