### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/geojson#42]
(or new maintainer _team_)

This package was archived on GitHub but not on CRAN.
If someone has interest in maintaining it, it won't be archived on CRAN.
We'd transfer it back to the ropensci GitHub organization.

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci-archive/admin

**Comment by maelle** [comment]
@ropensci/admin

**Comment by mdsumner** [comment]
new maintainer @mdsumner 0.3.5 is now on CRAN and built for Windows

**Comment by maelle** [comment]
Thank you!!
